# -*- mode: python ; coding: utf-8 -*-
# Saral Puantaj - PyInstaller Spec File
# Tek dosya (onefile) çalıştırılabilir oluşturur

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('docs/KULLANICI_KILAVUZU.md', '.')],
    hiddenimports=[
        'core',
        'core.database',
        'core.hesaplama',
        'core.signals',
        'core.version',
        'core.user_config',
        'core.app_logger',
        'core.update_check',
        'core.input_validators',
        'pages',
        'pages.dashboard',
        'pages.records',
        'pages.settings',
        'pages.personnel',
        'pages.payslip',
        'pages.upload',
        'pages.raporlar',
        'pages.avans',
        'pages.bes',
        'pages.izin',
        'pages.holidays',
        'pages.vardiya',
        'pages.disiplin',
        'migrations',
        'migrations.migrations',
        'migrations.ay_kilit',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.QtPrintSupport',
        'openpyxl',
        'openpyxl.cell._writer',
        'pandas',
        'reportlab',
        'reportlab.pdfgen',
        'reportlab.lib',
        'bcrypt',
        'sqlite3',
        'datetime',
        'calendar',
        'requests',
        'xlsxwriter',
        'webbrowser',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'pytest',
        'numba',
        'llvmlite',
        'matplotlib',
        'scipy',
        'IPython',
        'notebook',
        'tkinter',
        'test',
        'unittest',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='SaralPuantaj',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # GUI modu (konsol gizli)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='puantaj.ico',
    version_file=None,  # Windows için version info eklenebilir
)
